name: my-first-workflow
on: workflow_dispatch
jobs:
   first_jobs:
      runs-on: ubuntu-latest
      steps:
      - name: checkout-repo
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
      - name: welcome message
        run: | 
           sudo apt-get install cowsay -y 
           echo "my first github-action jobs"
           cat /etc/os-release
      - name: Generate ASCII artwork
        run: cowsay -f dragon "Run for cover, i am a dragon....RAWR" >> dragon.txt
   test_jobs:
     needs: first_jobs
     concurrency:
       group: production-deployment
       cancel-in-progress: true
     runs-on: ubuntu-latest
     steps:
      - name: sleep timeout 
        run: sleep 30
      - name: check the dragon file 
        run: grep -i "dragon" dragon.txt 
      

    

      