name: my-first-workflow
on: push 
jobs:
   first_jobs:
      runs-on: ubuntu-latest
      steps:
      - name: checkout-repo
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
      - name: welcome message
        run: "echo my first github-action jobs"
      - name: list file
        run: ls -lrth
      - name: server info
        run: cat /etc/os-release 
      - name: check the memory 
        run: free -h 
   

      