name: Ascii workflow 
on: workflow_dispatch
jobs:
    second_job: 

      concurrency:
        group: production-deployment
      strategy:
        fail-fast: true
        max-parallel: 2
        matrix:
          os: [ubunutu-latest, ubuntu-20.04, windows-latest]
          images: [hello-world, alpine]
          exclude:
            - images: alpine
              os: windows-latest
          include:
            - images: amd/alpine
              os: ubuntu-20.04 
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Excute the ascii script file
          run: |
            chmod +x .github/workflows/ascii.sh
            ./.github/workflows/ascii.sh
        - name: Dump github context
          env: 
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT" 

        - name: Upload dragon.txt to share with next job
          uses: actions/upload-artifact@v4
          with:
           name: dragon-file
           path: dragon.txt

    test_job:
      needs: second_job
      runs-on: ubuntu-latest
      steps:
        - name: sleep mode 
          run: sleep 10 
        - name: Upload dragon.txt to share with next job
          uses: actions/download-artifact@v4
          with:
           name: dragon-file
        - name: text file exist 
          run: grep -i "dragon" dragon.txt
