name: Ascii workflow 
on: push
jobs:
    second_job: 
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Debug list repo files
          run: ls -R 
        - name: Excute the ascii script file
          run: |
            chmod +x .github/workflows/ascii.sh
            ./.github/workflows/ascii.sh
        - name: Upload dragon.txt to share with next job
          uses: actions/upload-artifact@v4
          with:
           name: dragon-file
           path: dragon.txt

    test_job:
      needs: second_job
      runs-on: ubuntu-latest
      steps:
        - name: sleep mode 
          run: sleep 10 
        - name: Upload dragon.txt to share with next job
          uses: actions/download-artifact@v4
          with:
           name: dragon-file
           path: dragon.txt
        - name: text file exist 
          run: grep -i "dragon" dragon.txt
