name: Ascii workflow 
on: push
jobs:
    second_job: 
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Excute the ascii script file
          run: |
            chmod +x .github/workflow/ascii.sh
            ./.github/workflow/ascii.sh

    